### ISSUE TITLE
request: new add network config

### ISSUE THREAD

**Issue by fredericofs** [realies/wpa_cli_php#1]
Hello, this is amazing, and exactly what I want looking for my headless raspberry.
Can you develop it a little bit more, to allow the manual entry of ssid and pass to join a network?

**Comment by realies** [comment]
You should be able to add new networks to the config by doing the following:

`$wcp = new Wpa_cli();`
`$new_network_id = $wcp->add_network();`
`if(is_numeric($new_network_id)) {`
`  $wcp->set_network($new_network_id, "network-ssid", "network-password");`
`  $wcp->select_network($new_network_id);`
`  $wcp->save_config();`
` } else die("Could not add new network");`
